name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2.5.0
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}

    - name: Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=no root@45.77.168.135 << 'EOF'
          cd /home/ubuntu/logicnet-streamlit
          
          # Pull the latest code from the repository
          git pull origin main
          
          # Check if the 'env' folder exists, if not create a virtual environment
          if [ ! -d "env" ]; then
            python3 -m venv env
          fi
          
          # Activate virtual environment and install dependencies
          source env/bin/activate
          npm run install
          
          # Start the application
          npm run start
        EOF
